#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PinKeyboard.Droid.Resource", IsApplication=true)]

namespace PinKeyboard.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Circle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int emptyDigit = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int fullDigit = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001b
			public const int Backspace = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int bgimg = 2131099677;
			
			// aapt resource value: 0x7f060023
			public const int button = 2131099683;
			
			// aapt resource value: 0x7f060025
			public const int button1 = 2131099685;
			
			// aapt resource value: 0x7f06001c
			public const int clayout = 2131099676;
			
			// aapt resource value: 0x7f060020
			public const int edittext = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int edittext1 = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int img = 2131099682;
			
			// aapt resource value: 0x7f060003
			public const int iv1 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int iv2 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int iv3 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int iv4 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int iv5 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int iv6 = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int linearLayout2 = 2131099657;
			
			// aapt resource value: 0x7f06001f
			public const int llentry = 2131099679;
			
			// aapt resource value: 0x7f060000
			public const int myButton = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int pw = 2131099649;
			
			// aapt resource value: 0x7f060027
			public const int relativeLayout1 = 2131099687;
			
			// aapt resource value: 0x7f060024
			public const int revokebutton = 2131099684;
			
			// aapt resource value: 0x7f060026
			public const int rlforfrag = 2131099686;
			
			// aapt resource value: 0x7f06000a
			public const int space2 = 2131099658;
			
			// aapt resource value: 0x7f06001a
			public const int t0 = 2131099674;
			
			// aapt resource value: 0x7f06000e
			public const int t1 = 2131099662;
			
			// aapt resource value: 0x7f060019
			public const int t10 = 2131099673;
			
			// aapt resource value: 0x7f06000f
			public const int t2 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int t3 = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int t4 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int t5 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int t6 = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int t7 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int t8 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int t9 = 2131099672;
			
			// aapt resource value: 0x7f06000c
			public const int tableLayout1 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int tableRow1 = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int tableRow2 = 2131099665;
			
			// aapt resource value: 0x7f060015
			public const int tableRow3 = 2131099669;
			
			// aapt resource value: 0x7f06001e
			public const int thell = 2131099678;
			
			// aapt resource value: 0x7f060032
			public const int tv0 = 2131099698;
			
			// aapt resource value: 0x7f060028
			public const int tv1 = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int tv2 = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int tv3 = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int tv4 = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int tv5 = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int tv6 = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int tv7 = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int tv8 = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int tv9 = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int tvBackspace = 2131099697;
			
			// aapt resource value: 0x7f060033
			public const int tvEnter = 2131099699;
			
			// aapt resource value: 0x7f06000b
			public const int view1 = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int materialKeyboard = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Pin = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int pinKeyBoard = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int apppin = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int login = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
